version: '1'
services:
    app:
        image: php:8.3.11-fpm
        container_name: app
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: webserver
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - laravel

    db:
        image: mysql:8.0.39
        container_name: db
        environment:
            AllowEmptyPassword: "false"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
